# Generated by Django 5.0 on 2023-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
