# Generated by Django 5.0 on 2023-12-14 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_posts_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('1f0a240c-9657-4ec4-a23d-6db834169557'), editable=False, primary_key=True, serialize=False),
        ),
    ]
