# Generated by Django 5.0 on 2023-12-14 10:05

import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_posts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=pathlib.PureWindowsPath('F:/my projects/blog app/uploads/thumbnail')),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('d72b12cb-1557-4f7a-8898-eefe81a0545b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
